# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f2ee0c8a1f6f8f77b6d878f12739b0ce7c03e6cee87bfdcc9dc8559f793b6d0c07f4a80a235774bdd09836f03eaca7588c604f4cf56a0ee62de8086ece5dcd56

test:
  secret_key_base: c667d8f50dd4c4f1ce980d954ea00ff8f615179f23a8cef3e7709aad164404468b32f493aac0add275aef988699b79effb889cb7b6c846d1f24e4e1d7e016942

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
